// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpa-3CwGvREazv8kVve4cCrdAzWl4mk0',
    appId: '1:222090421168:web:00a8046caecab754ad2c75',
    messagingSenderId: '222090421168',
    projectId: 'resep-a3f28',
    authDomain: 'resep-a3f28.firebaseapp.com',
    storageBucket: 'resep-a3f28.firebasestorage.app',
    measurementId: 'G-X4XFZLEE1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUSnQ35yS48hM-rINUAqRt2rDFWv9nnas',
    appId: '1:222090421168:android:93aaf00e99e04d04ad2c75',
    messagingSenderId: '222090421168',
    projectId: 'resep-a3f28',
    storageBucket: 'resep-a3f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVL8Wx9JeQtG98eguMuA3J4ZEvcNb3DHA',
    appId: '1:222090421168:ios:bd7be021519d0b40ad2c75',
    messagingSenderId: '222090421168',
    projectId: 'resep-a3f28',
    storageBucket: 'resep-a3f28.firebasestorage.app',
    iosBundleId: 'com.example.resepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVL8Wx9JeQtG98eguMuA3J4ZEvcNb3DHA',
    appId: '1:222090421168:ios:bd7be021519d0b40ad2c75',
    messagingSenderId: '222090421168',
    projectId: 'resep-a3f28',
    storageBucket: 'resep-a3f28.firebasestorage.app',
    iosBundleId: 'com.example.resepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDpa-3CwGvREazv8kVve4cCrdAzWl4mk0',
    appId: '1:222090421168:web:14361a3c2ace36cead2c75',
    messagingSenderId: '222090421168',
    projectId: 'resep-a3f28',
    authDomain: 'resep-a3f28.firebaseapp.com',
    storageBucket: 'resep-a3f28.firebasestorage.app',
    measurementId: 'G-39FNQ631XL',
  );

}