// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEdAeFatbM37VGd2dcJSm2hnCcFGzBGec',
    appId: '1:475594493286:web:3bb6c2951c559bc8d64ca7',
    messagingSenderId: '475594493286',
    projectId: 'daftarbelanja-65f5b',
    authDomain: 'daftarbelanja-65f5b.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-65f5b-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-65f5b.firebasestorage.app',
    measurementId: 'G-483H8FZG92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4hDD75d07A4um0gtVAJPCpmOxBs-pHJA',
    appId: '1:475594493286:android:2192bf2716bfdc58d64ca7',
    messagingSenderId: '475594493286',
    projectId: 'daftarbelanja-65f5b',
    databaseURL: 'https://daftarbelanja-65f5b-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-65f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZ13gA5VLcLnbt2enXjpKK3Lyr78VLrg',
    appId: '1:475594493286:ios:5ac1413ddcc5a749d64ca7',
    messagingSenderId: '475594493286',
    projectId: 'daftarbelanja-65f5b',
    databaseURL: 'https://daftarbelanja-65f5b-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-65f5b.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZ13gA5VLcLnbt2enXjpKK3Lyr78VLrg',
    appId: '1:475594493286:ios:5ac1413ddcc5a749d64ca7',
    messagingSenderId: '475594493286',
    projectId: 'daftarbelanja-65f5b',
    databaseURL: 'https://daftarbelanja-65f5b-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-65f5b.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEdAeFatbM37VGd2dcJSm2hnCcFGzBGec',
    appId: '1:475594493286:web:92c1eb7f502986eed64ca7',
    messagingSenderId: '475594493286',
    projectId: 'daftarbelanja-65f5b',
    authDomain: 'daftarbelanja-65f5b.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-65f5b-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-65f5b.firebasestorage.app',
    measurementId: 'G-BR3V62DZ9D',
  );
}
