// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEuWia-Mimw3GNUpn_OXqDbP75zs9aBgI',
    appId: '1:368660491433:web:0148e59691f17fbd33cdb8',
    messagingSenderId: '368660491433',
    projectId: 'mdpgold-476ab',
    authDomain: 'mdpgold-476ab.firebaseapp.com',
    databaseURL: 'https://mdpgold-476ab-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-476ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtU6Yz7tZGzj_vdppa3lzera0WrA-ML8',
    appId: '1:368660491433:android:77fcceaae2bf9f7533cdb8',
    messagingSenderId: '368660491433',
    projectId: 'mdpgold-476ab',
    databaseURL: 'https://mdpgold-476ab-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-476ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX3omdsRMoymQJqwUST_uECQCgvTZOhC8',
    appId: '1:368660491433:ios:a3bab5c013c1794d33cdb8',
    messagingSenderId: '368660491433',
    projectId: 'mdpgold-476ab',
    databaseURL: 'https://mdpgold-476ab-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-476ab.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX3omdsRMoymQJqwUST_uECQCgvTZOhC8',
    appId: '1:368660491433:ios:a3bab5c013c1794d33cdb8',
    messagingSenderId: '368660491433',
    projectId: 'mdpgold-476ab',
    databaseURL: 'https://mdpgold-476ab-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-476ab.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEuWia-Mimw3GNUpn_OXqDbP75zs9aBgI',
    appId: '1:368660491433:web:c9117afd422f123733cdb8',
    messagingSenderId: '368660491433',
    projectId: 'mdpgold-476ab',
    authDomain: 'mdpgold-476ab.firebaseapp.com',
    databaseURL: 'https://mdpgold-476ab-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-476ab.firebasestorage.app',
  );
}
